### ISSUE TITLE
Action plan for DataverseNO cloud migration

### ISSUE THREAD

**Issue by philippconzett** [DataverseNO/docker.dataverse.no#27]
**Friday 24 March 16:00 CET**
- [ ] Disable login to local dataverse.no and test.dataverse.no.

**Monday 27 March & Tuesday 28 March**
Before we start migration:
- [ ] Carry out last geolocation clean-up in local installation. See [GitHub issue](https://github.com/DataverseNO/local.dataverse.no/issues/35).
- [ ] Carry out last Terms of Use clean-up in local installation. See [GitHub issue](https://github.com/DataverseNO/local.dataverse.no/issues/9).

Migration:
- [ ] ... [LOÏC/OBI/ROLF: ADD YOUR STUFF HERE]
- [ ] ...
- [ ] ...

**Before we go live:**
- [ ] Run file integrity check to make sure the copied files are identical with the files at original upload. See [GitHub issue](https://github.com/DataverseNO/docker.dataverse.no/issues/8).
- [ ] Set :ZipUploadFilesLimit to 1. See [GitHub issue](https://github.com/DataverseNO/docker.dataverse.no/issues/24).
- [ ] Philipp: Unlink erroneous links between HVL collection and TROLLing. See [GitHub issue](https://github.com/DataverseNO/local.dataverse.no/issues/3).
- [ ] ...

**Comment by philippconzett** [comment]
@Louis-wr We should do a file integrity check.
